### ISSUE TITLE
Quest book text leking and bluar by the text color

### ISSUE THREAD

**Issue by Kishan000777** [MelanX/GardenofGlass-QuestbookEdition#6]
Quest book text leking and bluar by the text color

**Comment by Kishan000777** [comment]
You want pic

**Comment by Kishan000777** [comment]
F why r you not see my issue

**Comment by MelanX** [comment]
I don’t understand the issue. I already saw it, but had no time to write. 
However, I’m not working on this modpack anymore. Don’t expect any updates on this, sorry.

**Comment by Kishan000777** [comment]
Ono
